#!/bin/bash

bat_number=0
bat_status=$(acpi -b | grep "Battery ${bat_number}" | sed s/[,%]//g)
if [ -z "$bat_status" ]; then
  exit 1
fi
charging_symbol=''
battery_symbol=''
color=''
charging_status=$(echo $bat_status | awk '{print $3}')
battery_percent=$(echo $bat_status | awk '{print $4}')
battery_time_remain=$(echo $bat_status | awk '{print $5}' | awk -F: '{print $1":"$2}')

if [ $charging_status = 'Charging' ]; then
  charging_symbol='ﮣ'
fi

if [ $battery_percent -lt 20 ]; then 
  battery_symbol=''
  color='\x04'
elif [ $battery_percent -lt 40 ]; then
  color='\x03'
  battery_symbol=''
elif [ $battery_percent -lt 60 ]; then
  battery_symbol=''
elif [ $battery_percent -lt 80 ]; then
  battery_symbol=''
elif [ $battery_percent -lt 100 ]; then
  battery_symbol=''
else 
  battery_symbol='';
fi

echo -e "$color$charging_symbol $battery_symbol $battery_percent% $battery_time_remain \x01"
