#!/usr/bin/env bash

getPass() {
  find $HOME/.password-store/ -type f | grep -ivE '\.gpg-id|\.git' | sed "s|$HOME/.password-store/||g" | sed 's|.gpg||g' | dmenu -l 10 -p "Password: " | xargs -r pass -c 
}

setWifi() {
  nmcli device wifi rescan && nmcli device wifi list | sed '1d' | awk '{if ($1 == "*") print $3, "*"; else print $2}' | dmenu -l 10 -p "Wifi: " | awk '{print $1}' | xargs -r nmcli device wifi connect
}

viewFonts() {
  fc-list | awk '{print $1}' | sed 's/://g' | dmenu -l 20 -p "Fonts: " | xargs -r display
}

openTmux() {
  tmux ls | dmenu -l 10 -p "Tmux: " | awk '{print $1}' | sed 's/://g' | xargs -r st -e tmux attach-session -t
}

killProcess() {
  ps -fe | dmenu -l 20 -p "Process: " | awk '{print $2}' | xargs -r kill 
}

killProcessS() {
  ss -tunap | dmenu -l 20 -p "Process: " | sed -n 's/.*pid=\([0-9]*\),.*/\1/p' | xargs -r kill
}

screenshot() {
  imageName="screen-shot-$(date | sed 's/\s/-/g').png"
  if [ ! -d ~/Documents/Photos/screenshots/ ]; then
    mkdir -p ~/Documents/Photos/screenshots/
  fi
  # need imagemagic
  import -window root $imageName

  mv $imageName ~/Documents/Photos/screenshots/
  notify-send "Screenshot taken" "~/Documents/Photos/screenshots/${imageName}"
}

if declare -f "$1" > /dev/null
then
  "$@"
 else
  cmd=$(declare -F | awk '{print $3}' | dmenu -l 20 -p "Available command: ")
  [ $? = 0 ] || exit
  sleep 0.5 && "$cmd"
fi


