#!/bin/bash

dte(){
  dte="$(date +"%A, %b %d   %l:%M%p")"
  echo -e " $dte"
}

upd(){
  upd=`checkupdates | wc -l`
  echo -e "⟳ $upd updates"
}

mem(){
  mem=`free | awk '/Mem/ {printf "%d MiB/%d MiB\n", $3 / 1024.0, $2 / 1024.0 }'`
  echo -e "$mem"
}

cpu(){
  read cpu a b c previdle rest < /proc/stat
  prevtotal=$((a+b+c+previdle))
  sleep 0.5
  read cpu a b c idle rest < /proc/stat
  total=$((a+b+c+idle))
  cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
  echo -e " $cpu%"
}

xsetroot -name "  $(wifi)  $(battery)  $(cpu)   $(memory)  $(dte)"
