#!/bin/bash

# rm -f /tmp/locked.png

# If `imagemagick` is not installed, use a blank screen.
# [[ -f /usr/bin/convert ]] &&
# scrot -m -z /tmp/base.png &&
# convert /tmp/base.png -blur 5x3 /tmp/locked.png

# i3lock -e -f -c 000000 -i /home/subhash/Pictures/Lockscreen/active.png
slock
