#!/bin/sh

declare options=("todo
public_note
private_note
")
declare dmenuSelect=""
declare fileName=""

dmenuSelect=$(echo -e "${options[@]}" | dmenu -i -p "Notes")

case "$dmenuSelect" in
  todo)
    fileName="$HOME/vimwiki/private/todo.md"
  ;;
  public_note)
    fileName="$HOME/vimwiki/public/index.md"
  ;;
  private_note)
    fileName="$HOME/vimwiki/private/index.md"
  ;;
  *)
    exit 1;
  ;;
esac

if [ -f $fileName ]; then
  st -e nvim $fileName
else
  notify-send "Please create a file $fileName"
fi
