#!/bin/bash

# customizable
FZF_COMMAND="fzf-tmux -p --delimiter=: --with-nth 3 --color=hl:2"

# do not change
TARGET_SPEC="#{session_name}:#{window_id}:#{window_name}"

# select pane
LINE=$(tmux list-windows -a -F "$TARGET_SPEC $LIST_DATA" | $FZF_COMMAND) || exit 0
# split the result
args=(${LINE//:/ })
# activate session/window/pane
tmux select-window -t ${args[1]} && tmux switch-client -t ${args[0]}
